grafana:
  enabled: true
  adminPassword: admin
  defaultDashboardsEnabled: true

  service:
    type: ClusterIP

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

alertmanager:
  enabled: true

  alertmanagerSpec:
    replicas: 1
    retention: 24h
    storage: {}

    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

prometheus:
  enabled: true

  prometheusSpec:
    replicas: 1
    retention: 6h
    scrapeInterval: 30s
    evaluationInterval: 30s

    storageSpec: {}

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 700m
        memory: 1200Mi

prometheusOperator:
  enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true

kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false
