grafana:
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false
  enabled: true
  adminPassword: admin
  defaultDashboardsEnabled: true

  service:
    type: ClusterIP

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

alertmanager:
  enabled: false

prometheus:
  enabled: true

  prometheusSpec:
    replicas: 1
    retention: 6h
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}

    storageSpec: {}

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 700m
        memory: 1200Mi

prometheusOperator:
  enabled: true

  tls:
    enabled: false

  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: false

kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false
