apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::191524136560:role/olivesafety-day2-ops-dev-api-role
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"eks.amazonaws.com/role-arn":"arn:aws:iam::191524136560:role/olivesafety-day2-ops-dev-api-role"},"name":"olivesafety-api-sa","namespace":"olivesafety"}}
  creationTimestamp: "2026-07-10T01:12:43Z"
  name: olivesafety-api-sa
  namespace: olivesafety
  resourceVersion: "8872"
  uid: 24d340eb-9715-4808-837d-7849c187a316
