apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olivesafety-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yerimm99/olivesafety-day2-ops.git
    targetRevision: main
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: olivesafety

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
