apiVersion: v1
kind: ConfigMap
metadata:
  name: olivesafety-api-config
  namespace: olivesafety
data:
  SPRING_PROFILES_ACTIVE: "dev"
  AWS_REGION: "ap-northeast-2"

  DB_URL: "jdbc:mysql://olivesafety-day2-ops-dev-mysql.cdtqdnpxmz0b.ap-northeast-2.rds.amazonaws.com:3306/olivesafety?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  DB_DRIVER: "com.mysql.cj.jdbc.Driver"

  REDIS_HOST: "olivesafety-day2-ops-dev-redis.gyamym.ng.0001.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"
