apiVersion: v1
kind: Service
metadata:
  name: olivesafety-api
  labels:
    app.kubernetes.io/name: olivesafety-api
  namespace: olivesafety
spec:
  type: ClusterIP
  selector:
    app: olivesafety-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
