apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: olivesafety-api-secret
  namespace: olivesafety
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: olivesafety-api-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: olivesafety/dev/api
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: olivesafety/dev/api
        property: DB_PASSWORD

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: olivesafety/dev/api
        property: REDIS_PASSWORD

    - secretKey: JWT_TOKEN_SECRET
      remoteRef:
        key: olivesafety/dev/api
        property: JWT_TOKEN_SECRET

    - secretKey: AWS_SNS_ARN
      remoteRef:
        key: olivesafety/dev/api
        property: AWS_SNS_ARN

    - secretKey: AWS_SQS_URL
      remoteRef:
        key: olivesafety/dev/api
        property: AWS_SQS_URL
