apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cluster-secret-store.yaml
  - external-secret.yaml

images:
  - name: olivesafety-api
    newName: 191524136560.dkr.ecr.ap-northeast-2.amazonaws.com/olivesafety-day2-ops-dev/olivesafety-api
    newTag: 55acdbf

patches:
  - path: serviceaccount-irsa-patch.yaml
  - path: deployment-replicas-patch.yaml
  - path: hpa-dev-patch.yaml
