apiVersion: v1
kind: ServiceAccount
metadata:
  name: olivesafety-api-sa
  namespace: olivesafety
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::191524136560:role/olivesafety-day2-ops-dev-api-role
